name: CI

on:
    pull_request:
    push:

jobs:
  coding-standards:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: "Install dependencies"
        run: make dev-init

      - name: "Check coding style"
        run: make cs-check

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: "Install dependencies"
        run: make dev-init

      - name: Generate KeyPair
        run: php bin/console lexik:jwt:generate-keypair

      - name: "Run tests"
        run: make tests
